name: ci

on:
  push:

jobs:
  scan:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - library/adminer
#          - library/adoptopenjdk
#          - library/aerospike
#          - library/almalinux
#          - library/alpine
#          - library/alt
#          - library/amazoncorretto
#          - library/amazonlinux
#          - library/arangodb
#          - library/archlinux
#          - library/backdrop
#          - library/bash
#          - library/bonita
#          - library/buildpack-deps
#          - library/busybox
#          - library/caddy
#          - library/cassandra
#          - library/celery
#          - library/centos
#          - library/chronograf
#          - library/cirros
#          - library/clearlinux
#          - library/clefos
#          - library/clojure
#          - library/composer
#          - library/consul
#          - library/convertigo
#          - library/couchbase
#          - library/couchdb
#          - library/crate
#          - library/crux
#          - library/dart
#          - library/debian
#          - library/django
#          - library/docker
#          - library/docker-dev
#          - library/drupal
#          - library/eclipse-mosquitto
#          - library/eclipse-temurin
#          - library/eggdrop
#          - library/elasticsearch
#          - library/elixir
#          - library/erlang
#          - library/euleros
#          - library/express-gateway
#          - library/fedora
#          - library/flink
#          - library/fluentd
#          - library/friendica
#          - library/fsharp
#          - library/gazebo
#          - library/gcc
#          - library/geonetwork
#          - library/ghost
#          - library/glassfish
#          - library/golang
#          - library/gradle
#          - library/groovy
#          - library/haproxy
#          - library/haskell
#          - library/haxe
#          - library/hello-seattle
#          - library/hello-world
#          - library/hipache
#          - library/hitch
#          - library/hola-mundo
#          - library/httpd
#          - library/hylang
#          - library/ibm-semeru-runtimes
#          - library/ibmjava
#          - library/influxdb
#          - library/iojs
#          - library/irssi
#          - library/java
#          - library/jenkins
#          - library/jetty
#          - library/jobber
#          - library/joomla
#          - library/jruby
#          - library/julia
#          - library/kaazing-gateway
#          - library/kapacitor
#          - library/kibana
#          - library/known
#          - library/kong
#          - library/lightstreamer
#          - library/logstash
#          - library/mageia
#          - library/mariadb
#          - library/matomo
#          - library/maven
#          - library/mediawiki
#          - library/memcached
#          - library/mongo
#          - library/mongo-express
#          - library/monica
#          - library/mono
#          - library/mysql
#          - library/nats
#          - library/nats-streaming
#          - library/neo4j
#          - library/neurodebian
#          - library/nextcloud
#          - library/nginx
#          - library/node
#          - library/notary
#          - library/nuxeo
#          - library/odoo
#          - library/open-liberty
#          - library/openjdk
#          - library/opensuse
#          - library/oraclelinux
#          - library/orientdb
#          - library/owncloud
#          - library/percona
#          - library/perl
#          - library/photon
#          - library/php
#          - library/php-zendserver
#          - library/phpmyadmin
#          - library/piwik
#          - library/plone
#          - library/postfixadmin
#          - library/postgres
#          - library/pypy
#          - library/python
#          - library/r-base
#          - library/rabbitmq
#          - library/rails
#          - library/rakudo-star
#          - library/rapidoid
#          - library/redis
#          - library/redmine
#          - library/registry
#          - library/rethinkdb
#          - library/rocket.chat
#          - library/ros
#          - library/ruby
#          - library/rust
#          - library/sapmachine
#          - library/scratch
#          - library/sentry
#          - library/silverpeas
#          - library/sl
#          - library/solr
#          - library/sonarqube
#          - library/sourcemage
#          - library/spiped
#          - library/storm
#          - library/swarm
#          - library/swift
#          - library/swipl
#          - library/teamspeak
#          - library/telegraf
#          - library/thrift
#          - library/tomcat
#          - library/tomee
#          - library/traefik
#          - library/ubuntu
#          - library/ubuntu-debootstrap
#          - library/ubuntu-upstart
#          - library/varnish
#          - library/vault
#          - library/websphere-liberty
#          - library/wordpress
#          - library/xwiki
#          - library/yourls
#          - library/znc
#          - library/zookeeper
    steps:
      -
        name: Get Docker JWT Token
        id: jwt
        run: |
          TOKEN=$(curl -s -H "Content-Type: application/json" "https://auth.docker.io/token?service=registry.docker.io&scope=repository:${{ matrix.image }}:pull" | jq -r .token)
          if [ -z ${TOKEN} -o ${TOKEN} == "null" ]; then
          echo "::error::Cannot retrieve token"
          exit 1
          fi
          echo ::set-output name=token::${TOKEN}
      -
        name: Get Docker Tags
        id: tags
        if: success()
        run: |
          TAG_LIST=$(curl -s -H "Authorization: Bearer ${{ steps.jwt.outputs.token }}" "https://index.docker.io/v2/${{ matrix.image }}/tags/list" | jq -rc '.tags[]')
          echo ::set-output name=list::${TAG_LIST}
      -
        name: Install Trivy
        run: |
          curl -SsL "https://github.com/aquasecurity/trivy/releases/download/v0.21.2/trivy_0.21.2_Linux-64bit.deb" -o "/tmp/trivy.deb"
          sudo dpkg -i /tmp/trivy.deb
          trivy --version
      -
        name: Docker Scan
        if: success()
        run: |
          for TAG in $(echo ${{ steps.tags.outputs.list }} | sed "s/,/ /g"); do
            trivy image --no-progress ${{ matrix.image }}:$TAG
          done
